### ISSUE TITLE
实例4的话，上拉的时候在还没弹下去的时候，点另一个tab会出现下拉刷新并且不会消失。

### ISSUE THREAD

**Issue by yangjianwei1223** [yujinjin/list-pull-loading#1]
![image](https://user-images.githubusercontent.com/12052982/42299095-d5382342-803b-11e8-9d51-70acfd060e39.png)

**Comment by yujinjin** [comment]
@yangjianwei1223 这个是由于上拉下拉加载组件的元素已经被隐藏导致获取当前滚动的最大高度是0，目前解决方案是当判断异常情况时去除滚动的动画效果。
已修复！
非常感谢你提出的问题。
