### ISSUE TITLE
上拉和下拉出现问题

### ISSUE THREAD

**Issue by qintong1101** [yujinjin/list-pull-loading#3]
![image](https://user-images.githubusercontent.com/26132748/46860077-2f358480-ce42-11e8-8ad5-36e0522b6cdc.png)
拉动的时候文字不会变化,而且不会触发回调

**Comment by qintong1101** [comment]
额  cli 3.0  忘了配置webpack了  配置了就能用了

**Comment by yujinjin** [comment]
@qintong1101  
一般情况下上拉下拉出现问题，先检查一下webpack配置，再看一下浏览器的控制台上是不是有errro抛出。
图片怎么没有显示出来？

**Comment by 236xzl** [comment]
我上拉下拉不能调用API，还有webpack在哪里配置的啊，配置什么？
