### ISSUE TITLE
你能不能给个接口禁用上拉加载

### ISSUE THREAD

**Issue by qq865738120** [yujinjin/list-pull-loading#5]
看了下源代码，里面给了滚动事件的监听接口，但是我测试绑定函数后不起作用。

**Comment by yujinjin** [comment]
HI， 请把事件绑定的代码贴一下！
事件的绑定方式是：<list-pull-loading @scroll="scrolling" ..></list-pull-loading>
@qq865738120

**Comment by qq865738120** [comment]
我是这么写的，也许是我项目哪里有问题。不过还是建议把api文档稍微完善一下，不写的话还得去看源码才知道。建议把上拉加载和下拉刷新都提供个接口，我相信这部分需求也是不少的，特别是下拉刷新很多时候是不需要的。

**Comment by qq865738120** [comment]
建议可以使用[finger-mover](https://github.com/HcySunYang/finger-mover)把项目重构下，这样你的源码会更简洁 @yujinjin

**Comment by yujinjin** [comment]
@qq865738120 谢谢你的建议，我会认真考虑的！
下拉刷新如果不需要，需配置down: false
上拉加载和下拉刷新可以用一个接口有传值（isLoadingMore：是否是重新加载），而具体用什么接口实现由业务场景自己来判断。
抱歉，应该是我的文档不够完善导致了你的困惑！

**Comment by qq865738120** [comment]
那我明白了，确实是文档没写好。
