### ISSUE TITLE
上拉下拉问题

### ISSUE THREAD

**Issue by 236xzl** [yujinjin/list-pull-loading#6]
我上拉下拉不能调用API，还有webpack在哪里配置的啊，配置什么？

**Comment by yujinjin** [comment]
@236xzl  是demo里不能调用API，还是自己的项目里。如果是自己的项目里不能调用请详细查看文档和demo，如果还没找到问题可以把调用的代码贴处理。
webpack的配置是在config目录下

**Comment by 236xzl** [comment]
我自己的项目，queryList只有在初始化的时候进入一次，不管上拉还是下拉不会进入第二次了

**Comment by yujinjin** [comment]
请确认一下你的queryList返回值
![image](https://user-images.githubusercontent.com/11609930/52025930-3099d280-2541-11e9-9a04-cfc4268df617.png)

**Comment by 236xzl** [comment]
![image](https://user-images.githubusercontent.com/3782783/52026027-76569b00-2541-11e9-8d49-b7b7933f4978.png)


这个数据是对的，是不是没有设置webpack的配置的原因

**Comment by yujinjin** [comment]
因为第一次就执行了queryList，应该不是webpack的配置的原因。
从代码上看
第一种情况是执行了else
第二种情况是resolve内的值小于maxResultCount，所以认为当前列表已经没有数据了。

**Comment by yujinjin** [comment]
demo里是列举一个简单的例子，实际的开发中不需要写那么多涌余的代码，接口查询是一个Promise就行了。
![image](https://user-images.githubusercontent.com/11609930/52026547-35f81c80-2543-11e9-8bdf-dca2681e5f82.png)

**Comment by 236xzl** [comment]
不太理解接口查询是一个Promise是什么意思

**Comment by 236xzl** [comment]
end\maxResultCount\skipCount这几个值分别是什么意思

**Comment by yujinjin** [comment]
1.Promise可以自行百度一下
2.end是demo中方便数据分页计算每次查询完还剩下多少条数据可以展示，至于maxResultCount\skipCount的概念建议多看一下API文档，里面有描述。

**Comment by 236xzl** [comment]
我现在有12条数据，一次展示10条，下拉可以理解哪里有问题，为什么上拉也不行呢

**Comment by 236xzl** [comment]
还有这个搜索怎么实现

**Comment by 236xzl** [comment]
resolve(end - parameters.skipCount); 这个方法的在什么情况下可以出现下拉和上拉

**Comment by 236xzl** [comment]
这个数据应该是对的，我上拉和下拉是出现了下拉加载更多的字样，但是就是不调用API

**Comment by lengyun102102** [comment]
我上拉也一直不行，不起作用，调试发现是scroll的 滚动事件怎么都不执行，目前在找原因。this.myScroll.on("scroll",function(){ 这个事件没执行

**Comment by lengyun102102** [comment]
我的问题和236xzl 用户一样，数据应该是对的，我上拉和下拉是出现了下拉加载更多的字样，但是就是不调用API，原因是因为this.myScroll.on("scroll",function(){ 这个事件没执行到

**Comment by yujinjin** [comment]
@lengyun102102  demo如果运行没问题,通常是因为list-pull-loading组件的滚动不是body上滚动而是在内部盒子里滚动，所以在定义内部的盒子高度，特别是页面内局部滚动。
